spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration
  datasource:
    url: jdbc:postgresql://postgres/match_db
    username: match_service
    password: "${postgres-match-service-password}"
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${keycloak.url}/realms/chess"
      client:
        registration:
          keycloak:
            client-id: cp_match_service
            client-secret: "${keycloak-match-service-client-secret}"
            client-authentication-method: client_secret_post
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: "${keycloak.url}/realms/chess"
            jwk-set-uri: "${keycloak.url}/realms/chess/protocol/openid-connect/certs"
            token-uri: "${keycloak.url}/realms/chess/protocol/openid-connect/token"

keycloak:
  url: http://keycloak:8080

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8080/eureka/

rabbitmq-messaging:
  queue:
    service: match_service_queue
  routing-key:
    service: match_service
    chess-service: chess_service
    user-service: user_service
  chess-service:
    events:
      exchange: chess_events_exchange
  user-service:
    events:
      exchange: user_events_exchange
